use crate::protocol::game::info::inventory::slotdata::SlotData;
use crate::protocol::serialization::serializer_error::SerializingErr;
use crate::protocol::serialization::{
	McDeserialize, McDeserializer, McSerialize, McSerializer, SerializingResult,
};
use crate::protocol_types::datatypes::game_types::Position;
use crate::protocol_types::datatypes::var_types::VarInt;
use sandstone_derive::VarIntEnum;

#[derive(VarIntEnum, Debug, Clone, PartialEq)]
#[repr(i32)]
pub enum VibrationSource {
	Block(Position) = 0,
	Entity(VarInt, f32) = 1,
}

#[derive(VarIntEnum, Debug, Clone, PartialEq)]
#[repr(i32)]
pub enum Particle {
	AngryVillager = 0,
	Block(VarInt) = 1,
	BlockMarker(VarInt) = 2,
	Bubble = 3,
	Cloud = 4,
	CopperFireFlame = 5,
	Crit = 6,
	DamageIndicator = 7,
	DragonBreath(f32) = 8,
	DrippingLava = 9,
	FallingLava = 10,
	LandingLava = 11,
	DrippingWater = 12,
	FallingWater = 13,
	Dust(i32, f32) = 14,
	DustColorTransition(i32, i32, f32) = 15,
	Effect(i32, f32) = 16,
	ElderGuardian = 17,
	EnchantedHit = 18,
	Enchant = 19,
	EndRod = 20,
	EntityEffect(i32) = 21,
	ExplosionEmitter = 22,
	Explosion = 23,
	Gust = 24,
	SmallGust = 25,
	GustEmitterLarge = 26,
	GustEmitterSmall = 27,
	SonicBoom = 28,
	FallingDust(VarInt) = 29,
	Firework = 30,
	Fishing = 31,
	Flame = 32,
	Infested = 33,
	CherryLeaves = 34,
	PaleOakLeaves = 35,
	TintedLeaves(i32) = 36,
	SculkSoul = 37,
	SculkCharge(f32) = 38,
	SculkChargePop = 39,
	SoulFireFlame = 40,
	Soul = 41,
	Flash(i32) = 42,
	HappyVillager = 43,
	Composter = 44,
	Heart = 45,
	InstantEffect(i32, f32) = 46,
	Item(SlotData) = 47,
	Vibration(VibrationSource, VarInt) = 48,
	Trail(f64, f64, f64, i32, VarInt) = 49,
	ItemSlime = 50,
	ItemCobweb = 51,
	ItemSnowball = 52,
	LargeSmoke = 53,
	Lava = 54,
	Mycelium = 55,
	Note = 56,
	Poof = 57,
	Portal = 58,
	Rain = 59,
	Smoke = 60,
	WhiteSmoke = 61,
	Sneeze = 62,
	Spit = 63,
	SquidInk = 64,
	SweepAttack = 65,
	TotemOfUndying = 66,
	Underwater = 67,
	Splash = 68,
	Witch = 69,
	BubblePop = 70,
	CurrentDown = 71,
	BubbleColumnUp = 72,
	Nautilus = 73,
	Dolphin = 74,
	CampfireCosySmoke = 75,
	CampfireSignalSmoke = 76,
	DrippingHoney = 77,
	FallingHoney = 78,
	LandingHoney = 79,
	FallingNectar = 80,
	FallingSporeBlossom = 81,
	Ash = 82,
	CrimsonSpore = 83,
	WarpedSpore = 84,
	SporeBlossomAir = 85,
	DrippingObsidianTear = 86,
	FallingObsidianTear = 87,
	LandingObsidianTear = 88,
	ReversePortal = 89,
	WhiteAsh = 90,
	SmallFlame = 91,
	Snowflake = 92,
	DrippingDripstoneLava = 93,
	FallingDripstoneLava = 94,
	DrippingDripstoneWater = 95,
	FallingDripstoneWater = 96,
	GlowSquidInk = 97,
	Glow = 98,
	WaxOn = 99,
	WaxOff = 100,
	ElectricSpark = 101,
	Scrape = 102,
	Shriek(VarInt) = 103,
	EggCrack = 104,
	DustPlume = 105,
	TrialSpawnerDetection = 106,
	TrialSpawnerDetectionOminous = 107,
	VaultConnection = 108,
	DustPillar(VarInt) = 109,
	OminousSpawning = 110,
	RaidOmen = 111,
	TrialOmen = 112,
	BlockCrumble(VarInt) = 113,
	Firefly = 114,
}