[package]
name = "mojang-api"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
reqwest = "0.12.20"
log = "0.4.27"
tokio = {version = "1.45.1", features = ["sync", "macros"]}
