//! Compile-time generator for the `mc-data` crate (blocks & items).
//!
//! This script fetches `blocks.json` and `items.json` from the PrismarineJS
//! [minecraft-data](https://github.com/PrismarineJS/minecraft-data) repository for the
//! requested Minecraft version, caches them under `minecraft-data-cache/<version>/` (a
//! committable, offline fallback), and generates `content_generated.rs` into `OUT_DIR`.
//!
//! The version is chosen from the `SANDSTONE_MC_VERSION` environment variable (a
//! `ProtocolVerison` fancy name such as `1.21.11`) and resolved to a data folder through
//! the repo's `dataPaths.json`. When unset it defaults to [`DEFAULT_MC_VERSION`].
//!
//! Network access is only required the first time a version is built; afterwards (and for
//! offline / docs.rs builds) the cached JSON is used.
//!
//! Enabling the `vendored` cargo feature skips the network entirely and builds straight
//! from the committed `minecraft-data-cache/` JSON (which must already be populated for the
//! target version).

use std::collections::HashSet;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

const DEFAULT_MC_VERSION: &str = "1.21.11";

/// Base URL for raw files in the minecraft-data repo `data/` directory.
const RAW_BASE: &str = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data";

fn main() {
	println!("cargo:rerun-if-env-changed=SANDSTONE_MC_VERSION");
	println!("cargo:rerun-if-changed=build.rs");

	let version = std::env::var("SANDSTONE_MC_VERSION").unwrap_or_else(|_| DEFAULT_MC_VERSION.to_string());
	// Set by cargo when the `vendored` feature is enabled: build from the cache, no network.
	let vendored = std::env::var("CARGO_FEATURE_VENDORED").is_ok();
	let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
	let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
	let cache_root = manifest_dir.join("minecraft-data-cache");

	// Resolve the data folders for this version via dataPaths.json.
	let data_paths_raw = obtain(&format!("{RAW_BASE}/dataPaths.json"), &cache_root.join("dataPaths.json"), vendored, "dataPaths.json");
	let data_paths: serde_json::Value = serde_json::from_str(&data_paths_raw).expect("dataPaths.json is valid JSON");

	let entry = data_paths
		.get("pc")
		.and_then(|pc| pc.get(&version))
		.unwrap_or_else(|| panic!("version `{version}` not found under `pc` in dataPaths.json"));
	let blocks_folder = entry.get("blocks").and_then(|v| v.as_str()).unwrap_or_else(|| panic!("no `blocks` data path for version `{version}`"));
	let items_folder = entry.get("items").and_then(|v| v.as_str()).unwrap_or_else(|| panic!("no `items` data path for version `{version}`"));

	let version_cache = cache_root.join(&version);

	let blocks_json = obtain(&format!("{RAW_BASE}/{blocks_folder}/blocks.json"), &version_cache.join("blocks.json"), vendored, "blocks.json");
	let items_json = obtain(&format!("{RAW_BASE}/{items_folder}/items.json"), &version_cache.join("items.json"), vendored, "items.json");

	// Embed the raw JSON so the library can parse it at runtime via include_str!.
	fs::write(out_dir.join("blocks.json"), &blocks_json).expect("write blocks.json to OUT_DIR");
	fs::write(out_dir.join("items.json"), &items_json).expect("write items.json to OUT_DIR");

	// Generate the per-entry namespaces.
	let blocks: Vec<Entry> = parse_entries(&blocks_json, "blocks.json");
	let items: Vec<Entry> = parse_entries(&items_json, "items.json");

	let blocks_ns = gen_namespace("Block", "BlockInfo", "block_by_id", &blocks, BLOCK_FIELDS);
	let items_ns = gen_namespace("Item", "ItemInfo", "item_by_id", &items, ITEM_FIELDS);

	let file: syn::File = syn::parse2(quote! { #blocks_ns #items_ns }).expect("generated tokens form a valid Rust file");
	let generated = format!("// @generated by build.rs from minecraft-data. Do not edit.\n\n{}", prettyplease::unparse(&file));

	fs::write(out_dir.join("content_generated.rs"), generated).expect("write content_generated.rs");

	println!("cargo:rustc-env=SANDSTONE_MC_VERSION_RESOLVED={version}");
}

/// A minimal view of a block/item used only for code generation.
struct Entry {
	id: i32,
	name: String,
	variant: String,
	/// The entry's non-null JSON fields. Drives which getters are emitted (a field counts as
	/// present only when it carries a real value) and supplies the literals baked into the
	/// `const fn` getters.
	json: serde_json::Map<String, serde_json::Value>,
}

/// Parses the `id` and `name` of every entry, retains its non-null fields, and assigns a unique
/// PascalCase struct name to each.
fn parse_entries(json: &str, what: &str) -> Vec<Entry> {
	let arr: Vec<serde_json::Value> = serde_json::from_str(json).unwrap_or_else(|e| panic!("{what} is not a JSON array: {e}"));

	let mut used: HashSet<String> = HashSet::new();
	arr.into_iter()
		.map(|v| {
			let obj = v.as_object().unwrap_or_else(|| panic!("{what}: entry is not a JSON object"));
			let id = obj.get("id").and_then(|x| x.as_i64()).unwrap_or_else(|| panic!("{what}: entry missing numeric `id`")) as i32;
			let name = obj.get("name").and_then(|x| x.as_str()).unwrap_or_else(|| panic!("{what}: entry missing `name`")).to_string();
			let variant = unique_variant(&name, &mut used);
			// Drop JSON `null`s (e.g. `hardness` on unbreakable blocks): a null value means the
			// getter is omitted entirely, just like an absent key.
			let json = obj.iter().filter(|(_, v)| !v.is_null()).map(|(k, v)| (k.clone(), v.clone())).collect();
			Entry { id, name, variant, json }
		})
		.collect()
}

/// How a getter's value is produced. Scalar/string/enum fields are baked into a `const fn`
/// returning a literal; heap-backed fields can't be `const` so they delegate to the runtime
/// data table.
enum Kind {
	I32,
	U32,
	U8,
	F32,
	Bool,
	Str,
	BoundingBox,
	/// Owned/heap field, returned by reference from the runtime table. `ret` is the return type
	/// and `expr` the body, operating on a `d: &'static <Info>` binding.
	Runtime { ret: &'static str, expr: &'static str },
}

/// One accessor to generate: the JSON key whose presence gates it, the getter name, and how its
/// value is produced.
struct FieldSpec {
	json_key: &'static str,
	getter: &'static str,
	kind: Kind,
}

/// Field accessors for blocks, mirroring [`crate::BlockInfo`].
const BLOCK_FIELDS: &[FieldSpec] = &[
	FieldSpec { json_key: "id", getter: "get_id", kind: Kind::I32 },
	FieldSpec { json_key: "name", getter: "get_name", kind: Kind::Str },
	FieldSpec { json_key: "displayName", getter: "get_display_name", kind: Kind::Str },
	FieldSpec { json_key: "hardness", getter: "get_hardness", kind: Kind::F32 },
	FieldSpec { json_key: "stackSize", getter: "get_stack_size", kind: Kind::U32 },
	FieldSpec { json_key: "diggable", getter: "get_diggable", kind: Kind::Bool },
	FieldSpec { json_key: "boundingBox", getter: "get_bounding_box", kind: Kind::BoundingBox },
	FieldSpec { json_key: "material", getter: "get_material", kind: Kind::Str },
	FieldSpec { json_key: "harvestTools", getter: "get_harvest_tools", kind: Kind::Runtime { ret: "&'static std::collections::HashMap<u32, bool>", expr: "d.harvestTools.as_ref().unwrap()" } },
	FieldSpec { json_key: "variations", getter: "get_variations", kind: Kind::Runtime { ret: "&'static [crate::blocks::Variation]", expr: "d.variations.as_deref().unwrap()" } },
	FieldSpec { json_key: "states", getter: "get_states", kind: Kind::Runtime { ret: "&'static [crate::blocks::BlockState]", expr: "d.states.as_deref().unwrap()" } },
	FieldSpec { json_key: "drops", getter: "get_drops", kind: Kind::Runtime { ret: "&'static [crate::blocks::Drop]", expr: "d.drops.as_slice()" } },
	FieldSpec { json_key: "transparent", getter: "get_transparent", kind: Kind::Bool },
	FieldSpec { json_key: "emitLight", getter: "get_emit_light", kind: Kind::U8 },
	FieldSpec { json_key: "filterLight", getter: "get_filter_light", kind: Kind::U8 },
	FieldSpec { json_key: "minStateId", getter: "get_min_state_id", kind: Kind::U32 },
	FieldSpec { json_key: "maxStateId", getter: "get_max_state_id", kind: Kind::U32 },
	FieldSpec { json_key: "defaultState", getter: "get_default_state", kind: Kind::U32 },
	FieldSpec { json_key: "resistance", getter: "get_resistance", kind: Kind::F32 },
];

/// Field accessors for items, mirroring [`crate::ItemInfo`].
const ITEM_FIELDS: &[FieldSpec] = &[
	FieldSpec { json_key: "id", getter: "get_id", kind: Kind::I32 },
	FieldSpec { json_key: "name", getter: "get_name", kind: Kind::Str },
	FieldSpec { json_key: "displayName", getter: "get_display_name", kind: Kind::Str },
	FieldSpec { json_key: "stackSize", getter: "get_stack_size", kind: Kind::U32 },
	FieldSpec { json_key: "enchantCategories", getter: "get_enchant_categories", kind: Kind::Runtime { ret: "&'static [::std::string::String]", expr: "d.enchantCategories.as_deref().unwrap()" } },
	FieldSpec { json_key: "maxDurability", getter: "get_max_durability", kind: Kind::U32 },
	FieldSpec { json_key: "repairWith", getter: "get_repair_with", kind: Kind::Runtime { ret: "&'static [::std::string::String]", expr: "d.repairWith.as_deref().unwrap()" } },
];

/// Builds the `(is_const, return_type, body_expr)` for one getter, baking the JSON `val` into a
/// literal for `const` kinds.
fn getter_parts(kind: &Kind, val: &serde_json::Value) -> (bool, TokenStream, TokenStream) {
	match kind {
		Kind::I32 => {
			let n = val.as_i64().expect("integer field") as i32;
			(true, quote!(i32), quote!(#n))
		}
		Kind::U32 => {
			let n = val.as_u64().expect("unsigned field") as u32;
			(true, quote!(u32), quote!(#n))
		}
		Kind::U8 => {
			let n = val.as_u64().expect("unsigned field") as u8;
			(true, quote!(u8), quote!(#n))
		}
		Kind::F32 => {
			let f = val.as_f64().expect("number field") as f32;
			// `{:?}` always renders a decimal point, so the suffixed literal is a valid `f32`.
			let lit: TokenStream = format!("{f:?}_f32").parse().expect("float literal parses");
			(true, quote!(f32), lit)
		}
		Kind::Bool => {
			let b = val.as_bool().expect("bool field");
			(true, quote!(bool), quote!(#b))
		}
		Kind::Str => {
			let s = val.as_str().expect("string field");
			(true, quote!(&'static str), quote!(#s))
		}
		Kind::BoundingBox => {
			let variant = match val.as_str().expect("boundingBox string") {
				"block" => format_ident!("Block"),
				"empty" => format_ident!("Empty"),
				other => panic!("unknown boundingBox `{other}`"),
			};
			(true, quote!(crate::blocks::BoundingBox), quote!(crate::blocks::BoundingBox::#variant))
		}
		Kind::Runtime { ret, expr } => {
			let ret: TokenStream = ret.parse().expect("field return type parses");
			let expr: TokenStream = expr.parse().expect("field access expression parses");
			(false, ret, expr)
		}
	}
}

/// Converts a snake_case minecraft name into a unique PascalCase Rust type name.
fn unique_variant(name: &str, used: &mut HashSet<String>) -> String {
	// Build PascalCase from alphanumeric segments.
	let mut base = String::new();
	for part in name.split(|c: char| !c.is_ascii_alphanumeric()) {
		if part.is_empty() {
			continue;
		}
		let mut chars = part.chars();
		let first = chars.next().unwrap();
		base.push(first.to_ascii_uppercase());
		base.extend(chars.map(|c| c.to_ascii_lowercase()));
	}
	if base.is_empty() {
		base.push_str("Unnamed");
	}
	if base.chars().next().unwrap().is_ascii_digit() {
		base.insert(0, '_');
	}

	if used.insert(base.clone()) {
		return base;
	}
	// Deterministically de-duplicate collisions.
	let mut n = 2;
	loop {
		let candidate = format!("{base}{n}");
		if used.insert(candidate.clone()) {
			return candidate;
		}
		n += 1;
	}
}

/// Generates a module (`module`) containing one unit struct per entry. Each struct exposes a
/// getter for every field it actually carries in the source JSON (per `fields`). Scalar/string
/// fields become `const fn`s returning a baked-in literal; heap-backed fields delegate to the
/// runtime metadata table (`struct_name`) via the crate-level lookup `by_id`.
///
/// This is what enables `Block::Bedrock::get_id()` style access.
fn gen_namespace(module: &str, struct_name: &str, by_id: &str, entries: &[Entry], fields: &[FieldSpec]) -> TokenStream {
	let mod_ident = format_ident!("{module}");
	let struct_ty = format_ident!("{struct_name}");
	let by_id_ident = format_ident!("{by_id}");
	let kind = module.to_ascii_lowercase();
	let mod_doc = format!("Type-safe namespace for every {kind}. Use `{module}::<Name>::get_id()` etc.");

	let structs = entries.iter().map(|e| {
		let variant = format_ident!("{}", e.variant);
		let struct_doc = format!("`{}` (id {})\n\nThis struct was autogenerated. Check the mc-data internal crate for more info.", e.name, e.id);

		let mut getters = Vec::new();
		let mut needs_data = false;
		for spec in fields {
			let Some(val) = e.json.get(spec.json_key) else { continue };
			let getter = format_ident!("{}", spec.getter);
			let doc = format!("The `{}` field of this {kind}.", spec.json_key);
			let (is_const, ret, body) = getter_parts(&spec.kind, val);
			if is_const {
				getters.push(quote! {
					#[doc = #doc]
					pub const fn #getter() -> #ret { #body }
				});
			} else {
				needs_data = true;
				getters.push(quote! {
					#[doc = #doc]
					pub fn #getter() -> #ret {
						let d = Self::data();
						#body
					}
				});
			}
		}

		// `data()` only exists to back the non-const getters; skip it when there are none.
		let data_fn = if needs_data {
			let id = e.id;
			quote! {
				/// The full metadata row backing the non-const getters on this type.
				fn data() -> &'static crate::#struct_ty {
					crate::#by_id_ident(#id).expect("generated id has matching data")
				}
			}
		} else {
			quote!()
		};

		quote! {
			#[doc = #struct_doc]
			pub struct #variant;
			impl #variant {
				#data_fn
				#(#getters)*
			}
		}
	});

	quote! {
		#[doc = #mod_doc]
		#[allow(non_snake_case, non_camel_case_types)]
		pub mod #mod_ident {
			#(#structs)*
		}
	}
}

/// Obtains a data file, honoring the `vendored` feature.
///
/// When `vendored` is set the cache is the only source: the committed copy is read directly
/// and a missing one is a hard error. Otherwise the network is tried first, falling back to
/// the cache on failure (see [`fetch_with_cache`]).
fn obtain(url: &str, cache_path: &Path, vendored: bool, what: &str) -> String {
	if vendored {
		return fs::read_to_string(cache_path).unwrap_or_else(|_| {
			panic!(
				"`vendored` feature is enabled but no cached {what} at {}. Run a normal \
                 (non-vendored) build once for this version to populate \
                 `minecraft-data-cache/`, then commit it.",
				cache_path.display()
			)
		});
	}
	fetch_with_cache(url, cache_path).unwrap_or_else(|e| panic!("could not obtain {what}: {e}"))
}

/// Fetches `url`, writing the body to `cache_path` on success. If the request fails but a
/// cached copy exists, returns the cached copy. Returns an error only if both fail.
fn fetch_with_cache(url: &str, cache_path: &Path) -> Result<String, Box<dyn Error>> {
	match fetch(url) {
		Ok(body) => {
			if let Some(parent) = cache_path.parent() {
				fs::create_dir_all(parent)?;
			}
			fs::write(cache_path, &body)?;
			Ok(body)
		}
		Err(e) => {
			if cache_path.exists() {
				println!("cargo:warning=fetch of {url} failed ({e}); using cached copy at {}", cache_path.display());
				Ok(fs::read_to_string(cache_path)?)
			} else {
				Err(format!("fetch of {url} failed ({e}) and no cache at {}", cache_path.display()).into())
			}
		}
	}
}

/// Performs a blocking HTTP GET and returns the response body as a string (ureq 3.x API).
fn fetch(url: &str) -> Result<String, Box<dyn Error>> {
	let body = ureq::get(url).call()?.body_mut().read_to_string()?;
	Ok(body)
}
