//! Compile-time generator for the `mc-data` crate (blocks & items).
//!
//! This script fetches `blocks.json` and `items.json` from the PrismarineJS
//! [minecraft-data](https://github.com/PrismarineJS/minecraft-data) repository for the
//! requested Minecraft version, caches them under `minecraft-data-cache/<version>/` (a
//! committable, offline fallback), and generates `content_generated.rs` into `OUT_DIR`.
//!
//! The version is chosen from the `SANDSTONE_MC_VERSION` environment variable (a
//! `ProtocolVerison` fancy name such as `1.21.11`) and resolved to a data folder through
//! the repo's `dataPaths.json`. When unset it defaults to [`DEFAULT_MC_VERSION`].
//!
//! Network access is only required the first time a version is built; afterwards (and for
//! offline / docs.rs builds) the cached JSON is used.
//!
//! Enabling the `vendored` cargo feature skips the network entirely and builds straight
//! from the committed `minecraft-data-cache/` JSON (which must already be populated for the
//! target version).

use std::collections::HashSet;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

/// Default Minecraft version, kept in sync with `ProtocolVerison::latest()`'s fancy name in
/// `sandstone/src/protocol_types/protocol_verison.rs`.
const DEFAULT_MC_VERSION: &str = "1.21.11";

/// Base URL for raw files in the minecraft-data repo `data/` directory.
const RAW_BASE: &str = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data";

fn main() {
	println!("cargo:rerun-if-env-changed=SANDSTONE_MC_VERSION");
	println!("cargo:rerun-if-changed=build.rs");

	let version = std::env::var("SANDSTONE_MC_VERSION").unwrap_or_else(|_| DEFAULT_MC_VERSION.to_string());
	// Set by cargo when the `vendored` feature is enabled: build from the cache, no network.
	let vendored = std::env::var("CARGO_FEATURE_VENDORED").is_ok();
	let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
	let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
	let cache_root = manifest_dir.join("minecraft-data-cache");

	// Resolve the data folders for this version via dataPaths.json.
	let data_paths_raw = obtain(&format!("{RAW_BASE}/dataPaths.json"), &cache_root.join("dataPaths.json"), vendored, "dataPaths.json");
	let data_paths: serde_json::Value = serde_json::from_str(&data_paths_raw).expect("dataPaths.json is valid JSON");

	let entry = data_paths
		.get("pc")
		.and_then(|pc| pc.get(&version))
		.unwrap_or_else(|| panic!("version `{version}` not found under `pc` in dataPaths.json"));
	let blocks_folder = entry.get("blocks").and_then(|v| v.as_str()).unwrap_or_else(|| panic!("no `blocks` data path for version `{version}`"));
	let items_folder = entry.get("items").and_then(|v| v.as_str()).unwrap_or_else(|| panic!("no `items` data path for version `{version}`"));

	let version_cache = cache_root.join(&version);

	let blocks_json = obtain(&format!("{RAW_BASE}/{blocks_folder}/blocks.json"), &version_cache.join("blocks.json"), vendored, "blocks.json");
	let items_json = obtain(&format!("{RAW_BASE}/{items_folder}/items.json"), &version_cache.join("items.json"), vendored, "items.json");

	// Embed the raw JSON so the library can parse it at runtime via include_str!.
	fs::write(out_dir.join("blocks.json"), &blocks_json).expect("write blocks.json to OUT_DIR");
	fs::write(out_dir.join("items.json"), &items_json).expect("write items.json to OUT_DIR");

	// Generate the per-entry namespaces.
	let blocks: Vec<Entry> = parse_entries(&blocks_json, "blocks.json");
	let items: Vec<Entry> = parse_entries(&items_json, "items.json");

	let mut generated = String::new();
	generated.push_str("// @generated by build.rs from minecraft-data. Do not edit.\n\n");
	generated.push_str(&gen_namespace("Block", "BlockInfo", "block_by_id", &blocks));
	generated.push_str(&gen_namespace("Item", "ItemInfo", "item_by_id", &items));

	fs::write(out_dir.join("content_generated.rs"), generated).expect("write content_generated.rs");

	println!("cargo:rustc-env=SANDSTONE_MC_VERSION_RESOLVED={version}");
}

/// A minimal view of a block/item used only for code generation.
struct Entry {
	id: i64,
	name: String,
	display_name: String,
	variant: String,
	/// State id range; present for blocks, absent for items.
	min_state_id: Option<i64>,
	max_state_id: Option<i64>,
}

/// Parses the `id`, `name`, and `displayName` of every entry, assigning a unique
/// PascalCase struct name to each.
fn parse_entries(json: &str, what: &str) -> Vec<Entry> {
	let arr: Vec<serde_json::Value> = serde_json::from_str(json).unwrap_or_else(|e| panic!("{what} is not a JSON array: {e}"));

	let mut used: HashSet<String> = HashSet::new();
	arr.into_iter()
		.map(|v| {
			let id = v.get("id").and_then(|x| x.as_i64()).unwrap_or_else(|| panic!("{what}: entry missing numeric `id`"));
			let name = v.get("name").and_then(|x| x.as_str()).unwrap_or_else(|| panic!("{what}: entry missing `name`")).to_string();
			let display_name = v.get("displayName").and_then(|x| x.as_str()).unwrap_or(&name).to_string();
			let variant = unique_variant(&name, &mut used);
			let min_state_id = v.get("minStateId").and_then(|x| x.as_i64());
			let max_state_id = v.get("maxStateId").and_then(|x| x.as_i64());
			Entry {
				id,
				name,
				display_name,
				variant,
				min_state_id,
				max_state_id,
			}
		})
		.collect()
}

/// Converts a snake_case minecraft name into a unique PascalCase Rust type name.
fn unique_variant(name: &str, used: &mut HashSet<String>) -> String {
	// Build PascalCase from alphanumeric segments.
	let mut base = String::new();
	for part in name.split(|c: char| !c.is_ascii_alphanumeric()) {
		if part.is_empty() {
			continue;
		}
		let mut chars = part.chars();
		let first = chars.next().unwrap();
		base.push(first.to_ascii_uppercase());
		base.extend(chars.map(|c| c.to_ascii_lowercase()));
	}
	if base.is_empty() {
		base.push_str("Unnamed");
	}
	if base.chars().next().unwrap().is_ascii_digit() {
		base.insert(0, '_');
	}

	if used.insert(base.clone()) {
		return base;
	}
	// Deterministically de-duplicate collisions.
	let mut n = 2;
	loop {
		let candidate = format!("{base}{n}");
		if used.insert(candidate.clone()) {
			return candidate;
		}
		n += 1;
	}
}

/// Generates a module (`module`) containing one unit struct per entry, each with
/// `get_id`/`get_name`/`get_display_name` accessors and an `info()` that returns the full
/// metadata struct (`struct_name`) via the crate-level lookup `by_id`.
///
/// This is what enables `Block::Bedrock::get_id()` style access.
fn gen_namespace(module: &str, struct_name: &str, by_id: &str, entries: &[Entry]) -> String {
	let kind = module.to_ascii_lowercase();
	let mut s = String::new();

	s.push_str(&format!("/// Type-safe namespace for every {kind}. Use `{module}::<Name>::get_id()` etc.\n"));
	s.push_str("#[allow(non_snake_case, non_camel_case_types)]\n");
	s.push_str(&format!("pub mod {module} {{\n"));

	for e in entries {
		s.push_str(&format!("    /// `{}` (id {})\n", e.name, e.id));
		s.push_str("    /// \n    /// This struct was autogenerated. Check the mc-data internal crate for more info.\n");
		s.push_str(&format!("    pub struct {};\n", e.variant));
		s.push_str(&format!("    impl {} {{\n", e.variant));
		s.push_str(&format!("        /// The numeric id of this {kind}.\n"));
		s.push_str(&format!("        pub const fn get_id() -> i32 {{ {} }}\n", e.id));
		s.push_str(&format!("        /// The registry name of this {kind}.\n"));
		s.push_str(&format!("        pub const fn get_name() -> &'static str {{ {:?} }}\n", e.name));
		s.push_str(&format!("        /// The human-readable display name of this {kind}.\n"));
		s.push_str(&format!("        pub const fn get_display_name() -> &'static str {{ {:?} }}\n", e.display_name));
		// State id range, only emitted for entries that carry it (i.e. blocks).
		if let Some(min) = e.min_state_id {
			s.push_str(&format!("        /// The minimum block state id of this {kind}.\n"));
			s.push_str(&format!("        pub const fn get_min_id() -> u32 {{ {min} }}\n"));
		}
		if let Some(max) = e.max_state_id {
			s.push_str(&format!("        /// The maximum block state id of this {kind}.\n"));
			s.push_str(&format!("        pub const fn get_max_id() -> u32 {{ {max} }}\n"));
		}
		s.push_str(&format!("        /// The full [`crate::{struct_name}`] metadata for this {kind}.\n"));
		s.push_str(&format!(
			"        pub fn info() -> &'static crate::{struct_name} {{ crate::{by_id}({}).expect(\"generated id has matching data\") }}\n",
			e.id
		));
		s.push_str("    }\n");
	}

	s.push_str("}\n\n");
	s
}

/// Obtains a data file, honoring the `vendored` feature.
///
/// When `vendored` is set the cache is the only source: the committed copy is read directly
/// and a missing one is a hard error. Otherwise the network is tried first, falling back to
/// the cache on failure (see [`fetch_with_cache`]).
fn obtain(url: &str, cache_path: &Path, vendored: bool, what: &str) -> String {
	if vendored {
		return fs::read_to_string(cache_path).unwrap_or_else(|_| {
			panic!(
				"`vendored` feature is enabled but no cached {what} at {}. Run a normal \
                 (non-vendored) build once for this version to populate \
                 `minecraft-data-cache/`, then commit it.",
				cache_path.display()
			)
		});
	}
	fetch_with_cache(url, cache_path).unwrap_or_else(|e| panic!("could not obtain {what}: {e}"))
}

/// Fetches `url`, writing the body to `cache_path` on success. If the request fails but a
/// cached copy exists, returns the cached copy. Returns an error only if both fail.
fn fetch_with_cache(url: &str, cache_path: &Path) -> Result<String, Box<dyn Error>> {
	match fetch(url) {
		Ok(body) => {
			if let Some(parent) = cache_path.parent() {
				fs::create_dir_all(parent)?;
			}
			fs::write(cache_path, &body)?;
			Ok(body)
		}
		Err(e) => {
			if cache_path.exists() {
				println!("cargo:warning=fetch of {url} failed ({e}); using cached copy at {}", cache_path.display());
				Ok(fs::read_to_string(cache_path)?)
			} else {
				Err(format!("fetch of {url} failed ({e}) and no cache at {}", cache_path.display()).into())
			}
		}
	}
}

/// Performs a blocking HTTP GET and returns the response body as a string (ureq 3.x API).
fn fetch(url: &str) -> Result<String, Box<dyn Error>> {
	let body = ureq::get(url).call()?.body_mut().read_to_string()?;
	Ok(body)
}
