//! Compile-time generator for the `content` module (blocks & items).
//!
//! This script fetches `blocks.json` and `items.json` from the PrismarineJS
//! [minecraft-data](https://github.com/PrismarineJS/minecraft-data) repository for the
//! requested Minecraft version, caches them under `minecraft-data-cache/<version>/` (a
//! committable, offline fallback), and generates `content_generated.rs` into `OUT_DIR`.
//!
//! The version is chosen from the `SANDSTONE_MC_VERSION` environment variable (a
//! `ProtocolVerison` fancy name such as `1.21.11`) and resolved to a data folder through
//! the repo's `dataPaths.json`. When unset it defaults to [`DEFAULT_MC_VERSION`].
//!
//! Network access is only required the first time a version is built; afterwards (and for
//! offline / docs.rs builds) the cached JSON is used.

use std::collections::HashSet;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

/// Default Minecraft version, kept in sync with `ProtocolVerison::latest()`'s fancy name
/// in `src/protocol_types/protocol_verison.rs`. Build is re-run if that file changes.
const DEFAULT_MC_VERSION: &str = "1.21.11";

/// Base URL for raw files in the minecraft-data repo `data/` directory.
const RAW_BASE: &str = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data";

fn main() {
    println!("cargo:rerun-if-env-changed=SANDSTONE_MC_VERSION");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/protocol_types/protocol_verison.rs");

    let version = std::env::var("SANDSTONE_MC_VERSION").unwrap_or_else(|_| DEFAULT_MC_VERSION.to_string());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
    let cache_root = manifest_dir.join("minecraft-data-cache");

    // Resolve the data folders for this version via dataPaths.json.
    let data_paths_raw = fetch_with_cache(
        &format!("{RAW_BASE}/dataPaths.json"),
        &cache_root.join("dataPaths.json"),
    )
    .expect("could not obtain dataPaths.json (no network and no cache)");
    let data_paths: serde_json::Value =
        serde_json::from_str(&data_paths_raw).expect("dataPaths.json is valid JSON");

    let entry = data_paths
        .get("pc")
        .and_then(|pc| pc.get(&version))
        .unwrap_or_else(|| panic!("version `{version}` not found under `pc` in dataPaths.json"));
    let blocks_folder = entry
        .get("blocks")
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("no `blocks` data path for version `{version}`"));
    let items_folder = entry
        .get("items")
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("no `items` data path for version `{version}`"));

    let version_cache = cache_root.join(&version);

    let blocks_json = fetch_with_cache(
        &format!("{RAW_BASE}/{blocks_folder}/blocks.json"),
        &version_cache.join("blocks.json"),
    )
    .expect("could not obtain blocks.json (no network and no cache)");
    let items_json = fetch_with_cache(
        &format!("{RAW_BASE}/{items_folder}/items.json"),
        &version_cache.join("items.json"),
    )
    .expect("could not obtain items.json (no network and no cache)");

    // Embed the raw JSON so the library can parse it at runtime via include_str!.
    fs::write(out_dir.join("blocks.json"), &blocks_json).expect("write blocks.json to OUT_DIR");
    fs::write(out_dir.join("items.json"), &items_json).expect("write items.json to OUT_DIR");

    // Generate the per-entry enums + cheap accessors.
    let blocks: Vec<Entry> = parse_entries(&blocks_json, "blocks.json");
    let items: Vec<Entry> = parse_entries(&items_json, "items.json");

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs from minecraft-data. Do not edit.\n\n");
    generated.push_str(&gen_enum("Blocks", "Block", "to_block", "block_by_id", &blocks));
    generated.push_str(&gen_enum("Items", "Item", "to_item", "item_by_id", &items));

    fs::write(out_dir.join("content_generated.rs"), generated).expect("write content_generated.rs");

    println!("cargo:rustc-env=SANDSTONE_MC_VERSION_RESOLVED={version}");
}

/// A minimal view of a block/item used only for code generation.
struct Entry {
    id: u64,
    name: String,
    display_name: String,
    variant: String,
}

/// Parses the `id`, `name`, and `displayName` of every entry, assigning a unique
/// PascalCase enum variant name to each.
fn parse_entries(json: &str, what: &str) -> Vec<Entry> {
    let arr: Vec<serde_json::Value> =
        serde_json::from_str(json).unwrap_or_else(|e| panic!("{what} is not a JSON array: {e}"));

    let mut used: HashSet<String> = HashSet::new();
    arr.into_iter()
        .map(|v| {
            let id = v.get("id").and_then(|x| x.as_u64()).unwrap_or_else(|| panic!("{what}: entry missing numeric `id`"));
            let name = v.get("name").and_then(|x| x.as_str()).unwrap_or_else(|| panic!("{what}: entry missing `name`")).to_string();
            let display_name = v.get("displayName").and_then(|x| x.as_str()).unwrap_or(&name).to_string();
            let variant = unique_variant(&name, &mut used);
            Entry { id, name, display_name, variant }
        })
        .collect()
}

/// Converts a snake_case minecraft name into a unique PascalCase Rust enum variant.
fn unique_variant(name: &str, used: &mut HashSet<String>) -> String {
    // Build PascalCase from alphanumeric segments.
    let mut base = String::new();
    for part in name.split(|c: char| !c.is_ascii_alphanumeric()) {
        if part.is_empty() {
            continue;
        }
        let mut chars = part.chars();
        let first = chars.next().unwrap();
        base.push(first.to_ascii_uppercase());
        base.extend(chars.map(|c| c.to_ascii_lowercase()));
    }
    if base.is_empty() {
        base.push_str("Unnamed");
    }
    if base.chars().next().unwrap().is_ascii_digit() {
        base.insert(0, '_');
    }

    if used.insert(base.clone()) {
        return base;
    }
    // Deterministically de-duplicate collisions.
    let mut n = 2;
    loop {
        let candidate = format!("{base}{n}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        n += 1;
    }
}

/// Generates a `#[derive]`d enum plus accessor impls for one entry kind.
fn gen_enum(enum_name: &str, struct_name: &str, to_full: &str, by_id: &str, entries: &[Entry]) -> String {
    let mut s = String::new();

    s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    s.push_str("#[allow(non_camel_case_types)]\n");
    s.push_str(&format!("pub enum {enum_name} {{\n"));
    for e in entries {
        s.push_str(&format!("    {},\n", e.variant));
    }
    s.push_str("}\n\n");

    s.push_str(&format!("impl {enum_name} {{\n"));

    // id()
    s.push_str("    /// The numeric id of this entry.\n");
    s.push_str("    pub fn id(&self) -> u32 {\n        match self {\n");
    for e in entries {
        s.push_str(&format!("            {enum_name}::{} => {},\n", e.variant, e.id));
    }
    s.push_str("        }\n    }\n\n");

    // name()
    s.push_str("    /// The registry name of this entry (e.g. `stone`).\n");
    s.push_str("    pub fn name(&self) -> &'static str {\n        match self {\n");
    for e in entries {
        s.push_str(&format!("            {enum_name}::{} => {:?},\n", e.variant, e.name));
    }
    s.push_str("        }\n    }\n\n");

    // display_name()
    s.push_str("    /// The human-readable display name of this entry (e.g. `Stone`).\n");
    s.push_str("    pub fn display_name(&self) -> &'static str {\n        match self {\n");
    for e in entries {
        s.push_str(&format!("            {enum_name}::{} => {:?},\n", e.variant, e.display_name));
    }
    s.push_str("        }\n    }\n\n");

    // all()
    s.push_str("    /// Every entry, in declaration (id) order.\n");
    s.push_str(&format!("    pub fn all() -> &'static [{enum_name}] {{\n        &[\n"));
    for e in entries {
        s.push_str(&format!("            {enum_name}::{},\n", e.variant));
    }
    s.push_str("        ]\n    }\n\n");

    // from_id()
    s.push_str("    /// Looks up an entry by its numeric id.\n");
    s.push_str(&format!("    pub fn from_id(id: u32) -> Option<{enum_name}> {{\n        match id {{\n"));
    for e in entries {
        s.push_str(&format!("            {} => Some({enum_name}::{}),\n", e.id, e.variant));
    }
    s.push_str("            _ => None,\n        }\n    }\n\n");

    // from_name()
    s.push_str("    /// Looks up an entry by its registry name.\n");
    s.push_str(&format!("    pub fn from_name(name: &str) -> Option<{enum_name}> {{\n        match name {{\n"));
    for e in entries {
        s.push_str(&format!("            {:?} => Some({enum_name}::{}),\n", e.name, e.variant));
    }
    s.push_str("            _ => None,\n        }\n    }\n\n");

    // to_block()/to_item()
    s.push_str(&format!("    /// Returns the full [`{struct_name}`] metadata for this entry.\n"));
    s.push_str(&format!("    pub fn {to_full}(&self) -> &'static {struct_name} {{\n"));
    s.push_str(&format!("        {by_id}(self.id()).expect(\"generated id has matching data\")\n"));
    s.push_str("    }\n");

    s.push_str("}\n\n");
    s
}

/// Fetches `url`, writing the body to `cache_path` on success. If the request fails but a
/// cached copy exists, returns the cached copy. Returns an error only if both fail.
fn fetch_with_cache(url: &str, cache_path: &Path) -> Result<String, Box<dyn Error>> {
    match fetch(url) {
        Ok(body) => {
            if let Some(parent) = cache_path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(cache_path, &body)?;
            Ok(body)
        }
        Err(e) => {
            if cache_path.exists() {
                println!("cargo:warning=fetch of {url} failed ({e}); using cached copy at {}", cache_path.display());
                Ok(fs::read_to_string(cache_path)?)
            } else {
                Err(format!("fetch of {url} failed ({e}) and no cache at {}", cache_path.display()).into())
            }
        }
    }
}

/// Performs a blocking HTTP GET and returns the response body as a string.
fn fetch(url: &str) -> Result<String, Box<dyn Error>> {
    let body = ureq::get(url).call()?.into_string()?;
    Ok(body)
}
