//! NBT file parsing large scale test.

#[cfg(test)]
mod test {
	use std::io::Read;

	use flate2::read::GzDecoder;
	use sandstone::protocol::serialization::McDeserializer;
	use sandstone::protocol_types::datatypes::nbt::{NbtCompound, NbtTag};

	/// The function used to generate the byte array values in bigtest.nbt
	fn expected_byte(n: usize) -> i8 {
		((n * n * 255 + n * 7) % 100) as i8
	}

	/// Parse the `bigtest.nbt` file. Decompress from gzip then test all values.
	#[test]
	fn test_parse_file() {
		let compressed = include_bytes!("assets/bigtest.nbt");

		let mut decoder = GzDecoder::new(&compressed[..]);
		let mut decompressed = Vec::new();
		decoder.read_to_end(&mut decompressed).expect("Failed to decompress bigtest.nbt");

		let mut deserializer = McDeserializer::new(&decompressed);
		let compound = NbtCompound::from_root(&mut deserializer).expect("Failed to parse bigtest.nbt");

		assert_eq!(compound.root_name, Some("Level".to_string()));

		// Primitives
		assert_eq!(compound["byteTest"], NbtTag::Byte(127));
		assert_eq!(compound["shortTest"], NbtTag::Short(32767));
		assert_eq!(compound["intTest"], NbtTag::Int(2147483647));
		assert_eq!(compound["longTest"], NbtTag::Long(9223372036854775807));
		assert_eq!(compound["floatTest"], NbtTag::Float(0.49823147));
		assert_eq!(compound["doubleTest"], NbtTag::Double(0.4931287132182315));
		assert_eq!(compound["stringTest"], NbtTag::String("HELLO WORLD THIS IS A TEST STRING ÅÄÖ!".to_string()));

		// Byte array: 1000 values generated by the documented formula.
		let byte_array_key = "byteArrayTest (the first 1000 values of (n*n*255+n*7)%100, starting with n=0 (0, 62, 34, 16, 8, ...))";
		let NbtTag::ByteArray(byte_array) = &compound[byte_array_key] else {
			panic!("Expected byteArrayTest to be a ByteArray");
		};
		assert_eq!(byte_array.list.len(), 1000);
		for (n, value) in byte_array.list.iter().enumerate() {
			assert_eq!(*value, expected_byte(n), "byteArrayTest mismatch at index {n}");
		}

		// List of longs
		let NbtTag::List(long_list) = &compound["listTest (long)"] else {
			panic!("Expected listTest (long) to be a List");
		};
		assert_eq!(long_list.list, vec![NbtTag::Long(11), NbtTag::Long(12), NbtTag::Long(13), NbtTag::Long(14), NbtTag::Long(15)]);

		// List of compounds
		let NbtTag::List(compound_list) = &compound["listTest (compound)"] else {
			panic!("Expected listTest (compound) to be a List");
		};
		assert_eq!(compound_list.list.len(), 2);
		for (i, tag) in compound_list.list.iter().enumerate() {
			let NbtTag::Compound(c) = tag else {
				panic!("Expected listTest (compound) entry to be a Compound");
			};
			assert_eq!(c["created-on"], NbtTag::Long(1264099775885));
			assert_eq!(c["name"], NbtTag::String(format!("Compound tag #{i}")));
		}

		// Nested compounds
		let NbtTag::Compound(nested) = &compound["nested compound test"] else {
			panic!("Expected nested compound test to be a Compound");
		};
		let NbtTag::Compound(ham) = &nested["ham"] else {
			panic!("Expected ham to be a Compound");
		};
		assert_eq!(ham["name"], NbtTag::String("Hampus".to_string()));
		assert_eq!(ham["value"], NbtTag::Float(0.75));
		let NbtTag::Compound(egg) = &nested["egg"] else {
			panic!("Expected egg to be a Compound");
		};
		assert_eq!(egg["name"], NbtTag::String("Eggbert".to_string()));
		assert_eq!(egg["value"], NbtTag::Float(0.5));
	}
}