[package]
name = "status_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
sandstone = {path = "../../../sandstone"}
tokio = {version = "1.45.0", features = ["full", "macros"]}
simple_logger = "5.0.0"
log = "0.4.27"
image = "0.25.6"